CREATE TABLE IF NOT EXISTS api_products (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  description TEXT NOT NULL,
  target_users TEXT NOT NULL,
  available_plans TEXT NOT NULL,
  method TEXT NOT NULL,
  endpoint TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  sample_request TEXT,
  sample_response TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT OR IGNORE INTO api_products (
  slug,
  name,
  category,
  description,
  target_users,
  available_plans,
  method,
  endpoint,
  status,
  sample_request,
  sample_response
) VALUES
(
  'health-risk-score',
  'Health Risk Score API',
  'Risk Analysis',
  'ประเมินระดับความเสี่ยงสุขภาพเบื้องต้นจากอายุ BMI น้ำตาล คอเลสเตอรอล และความดัน',
  'Insurance,Hospital,Health App',
  'silver,gold',
  'POST',
  '/api/v1/analysis/risk-score',
  'active',
  '{"age":35,"bmi":27.4,"bloodSugar":118,"cholesterol":210,"systolicBP":138,"diastolicBP":88,"smoking":false,"exerciseFreqPerWeek":1}',
  '{"status":"success","message":"risk score calculated","data":{"score":60,"riskLevel":"high"}}'
),
(
  'insurance-risk-screening',
  'Insurance Risk Screening API',
  'Insurance Scoring',
  'คัดกรองความเสี่ยงเบื้องต้นสำหรับการประเมินด้านประกันสุขภาพ',
  'Insurance',
  'gold',
  'POST',
  '/api/v1/analysis/insurance-score',
  'active',
  '{"age":42,"bmi":29.1,"bloodSugar":125}',
  '{"status":"success","message":"insurance score calculated","data":{"score":78,"riskLevel":"high"}}'
),
(
  'health-service-search',
  'Health Service Search API',
  'Service Search',
  'ค้นหาบริการตรวจสุขภาพและแพ็กเกจบริการสุขภาพตามหมวดหมู่และราคา',
  'Hospital,Health App',
  'basic,silver,gold',
  'GET',
  '/api/v1/services',
  'active',
  '{"q":"blood","minPrice":1000,"maxPrice":3000}',
  '{"data":[{"id":1,"name":"Advanced Blood Test"}]}'
),
(
  'health-recommendation',
  'Health Recommendation API',
  'Recommendation',
  'แนะนำแนวทางดูแลสุขภาพเบื้องต้นจากผลการประเมินความเสี่ยง',
  'Hospital,Health App',
  'silver,gold',
  'POST',
  '/api/v1/recommendation',
  'active',
  '{"riskLevel":"medium","age":35}',
  '{"data":{"recommendations":["ควรออกกำลังกายอย่างน้อย 3 ครั้งต่อสัปดาห์"]}}'
);
INSERT OR IGNORE INTO api_products (
  slug,
  name,
  category,
  description,
  target_users,
  available_plans,
  method,
  endpoint,
  status,
  sample_request,
  sample_response
) VALUES
(
  'basic-bmi-calculator',
  'BMI Calculator API',
  'Basic Health',
  'คำนวณค่า BMI และแปลผลเบื้องต้นจากน้ำหนักและส่วนสูง',
  'Health App,Fitness App',
  'basic,silver,gold',
  'POST',
  '/api/v1/basic/bmi',
  'active',
  '{"weightKg":68,"heightCm":170}',
  '{"status":"success","data":{"bmi":23.5,"category":"normal"}}'
),
(
  'basic-blood-pressure-check',
  'Blood Pressure Check API',
  'Basic Health',
  'ประเมินระดับความดันโลหิตเบื้องต้นจากค่า systolic และ diastolic',
  'Health App,Hospital',
  'basic,silver,gold',
  'POST',
  '/api/v1/basic/blood-pressure',
  'active',
  '{"systolicBP":128,"diastolicBP":82}',
  '{"status":"success","data":{"level":"elevated","message":"ควรติดตามค่าความดันอย่างสม่ำเสมอ"}}'
),
(
  'basic-health-package-list',
  'Health Package List API',
  'Service Search',
  'ดึงรายการแพ็กเกจตรวจสุขภาพพื้นฐานสำหรับแสดงในแอปหรือเว็บไซต์',
  'Hospital,Health App',
  'basic,silver,gold',
  'GET',
  '/api/v1/services/packages',
  'active',
  '{"category":"general-checkup"}',
  '{"status":"success","data":[{"id":1,"name":"Basic Checkup","price":1200}]}'
),
(
  'basic-clinic-finder',
  'Clinic Finder API',
  'Service Search',
  'ค้นหาคลินิกหรือสถานพยาบาลเบื้องต้นตามพื้นที่และประเภทบริการ',
  'Health App,Hospital',
  'basic,silver,gold',
  'GET',
  '/api/v1/services/clinics',
  'active',
  '{"province":"Bangkok","serviceType":"blood-test"}',
  '{"status":"success","data":[{"name":"Health Clinic A","province":"Bangkok"}]}'
),
(
  'basic-water-intake-estimator',
  'Water Intake Estimator API',
  'Basic Health',
  'ประเมินปริมาณน้ำที่ควรดื่มต่อวันจากน้ำหนักตัวและกิจกรรม',
  'Fitness App,Health App',
  'basic,silver,gold',
  'POST',
  '/api/v1/basic/water-intake',
  'active',
  '{"weightKg":60,"activityLevel":"medium"}',
  '{"status":"success","data":{"recommendedLitersPerDay":2.4}}'
),
(
  'silver-lab-result-interpretation',
  'Lab Result Interpretation API',
  'Lab Analysis',
  'ช่วยแปลผลตรวจสุขภาพเบื้องต้น เช่น น้ำตาล ไขมัน และค่าตับ',
  'Hospital,Health App,Insurance',
  'silver,gold',
  'POST',
  '/api/v1/analysis/lab-interpretation',
  'active',
  '{"fastingBloodSugar":112,"cholesterol":215,"alt":45,"ast":38}',
  '{"status":"success","data":{"summary":"พบค่าน้ำตาลและไขมันสูงเล็กน้อย","riskFlags":["blood_sugar","cholesterol"]}}'
),
(
  'silver-metabolic-risk',
  'Metabolic Risk API',
  'Risk Analysis',
  'ประเมินความเสี่ยงกลุ่มโรคเมตาบอลิกจาก BMI รอบเอว น้ำตาล ไขมัน และความดัน',
  'Hospital,Health App,Insurance',
  'silver,gold',
  'POST',
  '/api/v1/analysis/metabolic-risk',
  'active',
  '{"bmi":28.2,"waistCm":92,"bloodSugar":118,"triglyceride":180,"systolicBP":135}',
  '{"status":"success","data":{"riskLevel":"medium","score":64}}'
),
(
  'silver-personalized-health-tips',
  'Personalized Health Tips API',
  'Recommendation',
  'สร้างคำแนะนำสุขภาพแบบเฉพาะบุคคลจากข้อมูลพื้นฐานและผลตรวจ',
  'Health App,Fitness App',
  'silver,gold',
  'POST',
  '/api/v1/recommendation/personalized-tips',
  'active',
  '{"age":32,"bmi":26.1,"riskLevel":"medium","exerciseFreqPerWeek":1}',
  '{"status":"success","data":{"tips":["เพิ่มการออกกำลังกายเป็น 3 ครั้งต่อสัปดาห์","ควบคุมอาหารหวานและมัน"]}}'
),
(
  'silver-health-trend-summary',
  'Health Trend Summary API',
  'Health Records',
  'สรุปแนวโน้มสุขภาพจากประวัติผลตรวจหลายครั้ง เช่น น้ำตาล ไขมัน และความดัน',
  'Hospital,Health App',
  'silver,gold',
  'POST',
  '/api/v1/records/trend-summary',
  'active',
  '{"patientId":12,"metrics":["bloodSugar","cholesterol","systolicBP"]}',
  '{"status":"success","data":{"trend":"worsening","summary":"ค่าน้ำตาลและความดันมีแนวโน้มสูงขึ้น"}}'
),
(
  'silver-follow-up-reminder',
  'Follow-up Reminder API',
  'Patient Engagement',
  'แนะนำช่วงเวลาติดตามผลตรวจหรือพบแพทย์ตามระดับความเสี่ยง',
  'Hospital,Health App',
  'silver,gold',
  'POST',
  '/api/v1/recommendation/follow-up',
  'active',
  '{"riskLevel":"high","lastCheckupDate":"2026-04-01"}',
  '{"status":"success","data":{"recommendedFollowUp":"ภายใน 30 วัน","priority":"high"}}'
),
(
  'gold-ai-health-insight',
  'AI Health Insight API',
  'Advanced AI Analysis',
  'วิเคราะห์ข้อมูลสุขภาพหลายมิติและสรุป insight เชิงลึกสำหรับองค์กร',
  'Insurance,Hospital,Enterprise Health Platform',
  'gold',
  'POST',
  '/api/v1/ai/health-insight',
  'active',
  '{"age":45,"bmi":30.2,"bloodSugar":130,"cholesterol":240,"claimsHistory":true,"exerciseFreqPerWeek":0}',
  '{"status":"success","data":{"insight":"มีความเสี่ยงสูงด้าน metabolic และ lifestyle","recommendedAction":"priority intervention"}}'
),
(
  'gold-claims-risk-prediction',
  'Claims Risk Prediction API',
  'Insurance Scoring',
  'คาดการณ์ความเสี่ยงการเคลมประกันสุขภาพจากข้อมูลสุขภาพและประวัติความเสี่ยง',
  'Insurance',
  'gold',
  'POST',
  '/api/v1/insurance/claims-risk',
  'active',
  '{"age":50,"bmi":31.5,"chronicDisease":true,"smoking":true}',
  '{"status":"success","data":{"claimsRiskScore":86,"riskTier":"very_high"}}'
),
(
  'gold-enterprise-segment-analysis',
  'Enterprise Health Segment Analysis API',
  'Enterprise Analytics',
  'จัดกลุ่มผู้ใช้งานตามความเสี่ยงสุขภาพเพื่อใช้วิเคราะห์ระดับองค์กร',
  'Enterprise Health Platform,Insurance,Hospital',
  'gold',
  'POST',
  '/api/v1/analytics/health-segments',
  'active',
  '{"organizationId":101,"segmentBy":["age","riskLevel","bmi"]}',
  '{"status":"success","data":{"segments":[{"name":"high-risk adults","count":320},{"name":"low-risk young adults","count":540}]}}'
),
(
  'gold-advanced-lab-correlation',
  'Advanced Lab Correlation API',
  'Advanced Lab Analysis',
  'วิเคราะห์ความสัมพันธ์ของผลตรวจหลายค่าเพื่อประเมินความเสี่ยงเชิงลึก',
  'Hospital,Insurance',
  'gold',
  'POST',
  '/api/v1/analysis/lab-correlation',
  'active',
  '{"bloodSugar":126,"hdl":38,"ldl":160,"triglyceride":210,"alt":55}',
  '{"status":"success","data":{"correlationFlags":["metabolic_syndrome","fatty_liver_risk"],"riskLevel":"high"}}'
),
(
  'gold-population-health-dashboard',
  'Population Health Dashboard API',
  'Enterprise Analytics',
  'สรุปข้อมูลสุขภาพภาพรวมของกลุ่มประชากรสำหรับ dashboard องค์กร',
  'Hospital,Insurance,Enterprise Health Platform',
  'gold',
  'POST',
  '/api/v1/analytics/population-health',
  'active',
  '{"groupId":"company-001","dateRange":{"from":"2026-01-01","to":"2026-04-30"}}',
  '{"status":"success","data":{"totalUsers":1200,"highRiskPercent":18.5,"topRiskFactors":["high_bmi","high_cholesterol"]}}'
);